### ISSUE TITLE
parser bug in return of template string containing trailing backslash

### ISSUE THREAD

**Issue by kzc** [fabiosantoscode/uglify-es#10]
**Bug report or feature request?** 

bug

originally reported in: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/279

**Uglify version (`uglifyjs -V`)**

`@fabiosantoscode/uglify-es 3.6.0`

**JavaScript input**

```
$ cat test.js
var msg = getMsg({value: 1});
console.log(`${ msg } <= should not be undefined`);
function getMsg({value}) {
// Doesn't seem to repro if there is no multiline here
  return `\
${value}`;
}
```
Expected:
```
$ cat test.js | node
1 <= should not be undefined
```
Actual:
```
$ cat test.js | bin/uglifyjs -b | node
undefined <= should not be undefined
```
```
$ cat test.js | bin/uglifyjs -b
var msg = getMsg({
    value: 1
});

console.log(`${msg} <= should not be undefined`);

function getMsg({value: value}) {
    return;
    `${value}`;
}
```

**Comment by kzc** [comment]
One workaround is to use the `acorn` parser:

```
$ cat test.js | bin/uglifyjs -p acorn -mc | node
1 <= should not be undefined
```
```
$ cat test.js | node_modules/.bin/acorn | bin/uglifyjs -p spidermonkey -mc | node
1 <= should not be undefined
```

**Comment by boris-petrov** [comment]
@fabiosantoscode - why don't you just give @kzc commit rights instead of him/her pasting patches and you merging them all the time - it's going to save you both time? :)

**Comment by kzc** [comment]
No thanks. Just wanted to help to get this fork stable.

**Comment by boris-petrov** [comment]
@kzc - and we all appreciate and thank you for that! Whatever you decide. Thanks for the help - you're pretty much the only one in the world that can do so much with this project. :)

**Comment by kzc** [comment]
You're welcome.

> you're pretty much the only one in the world that can do really a lot for this project.

Not at all. There's around a dozen source files in the uglify `lib/` and `bin/` directories written in plain old ES5. It's just a matter of isolating and minimizing test cases, reading code and adding `console.error` statements to debug it. I encourage anyone to contribute.
