### ISSUE TITLE
need to resolve or disable Scrutinizer for PRs and commits

### ISSUE THREAD

**Issue by kzc** [fabiosantoscode/uglify-es#13]
Travis CI tests are green for all node versions. Scrutinizer tests appeared for first time a few days ago - how to disable?

https://github.com/fabiosantoscode/uglify-es/commit/226c0871be3675c5fc9a8b38d10fc5f0428f266d#commitcomment-28780978

**Comment by fabiosantoscode** [comment]
It looked like something useful. Though it has to work under node 0.8 and our name "@fabiosantoscode/uglify-es" is not a valid module name.

Removed it.

**Comment by kzc** [comment]
I think we can discontinue node 0.8 support if that will help. The lowest version supported and tested is node 0.10.

Or just disable Scrutinizer altogether if that's easier.

**Comment by kzc** [comment]
Thanks!
