### ISSUE TITLE
Publish permissions for @kzc

### ISSUE THREAD

**Issue by fabiosantoscode** [fabiosantoscode/uglify-es#27]
@kzc if you'd like me to give you publish permissions on the package, state your npm username!

**Comment by kzc** [comment]
@fabiosantoscode Thanks, but I'll pass. I'm basically done with minification. Just wanted to help with the transition. 

This project seems to be in pretty good shape now. Hopefully the upstream bug fix merge didn't break any ES6+ functionality.

Best of luck!

**Comment by fabiosantoscode** [comment]
Thanks and cheers!
