### ISSUE TITLE
Continuously merge mishoo/UglifyJS2/master into fabiosantoscode/uglify-es/master

### ISSUE THREAD

**Issue by boris-petrov** [fabiosantoscode/uglify-es#5]
This was done before the original project was abandoned. That is, `mishoo/UglifyJS2/harmony` was always rebased on `mishoo/UglifyJS2/master`. Perhaps it's not a bad idea to do so now as well - some of the things from the ES5 code would definitely apply to ES6 too.

**Comment by fabiosantoscode** [comment]
Agreed. We can cherry pick some paths but keeping up 100% is impossible.

**Comment by boris-petrov** [comment]
@kzc, @fabiosantoscode - I understand, that makes sense. How about only copying the whole testsuite then? There should be no conflicts when doing that and also that would allow easier finding and merging of commits that fix bugs. And of course it will prevent regressions.

**Comment by kzc** [comment]
@boris-petrov This is a volunteer effort. Feel free to file bug reports or submit PRs for review.

**Comment by fabiosantoscode** [comment]
I actually think following the tests is a nice idea. We don't change them much in the same places so it could be feasible to acquire them. And that would indeed keep track of whether issues in the original repo are sorted out.

**Comment by kzc** [comment]
Should someone elect to do that, the test output in this fork need not produce the same code necessarily - `expect_stdout` matching is all that matters. Also keep in mind that some `minify` options have been changed upstream in `uglify-js`, so there will be some divergence.
