### ISSUE TITLE
uglify-es compress conditionals: increment erroneously not reached

### ISSUE THREAD

**Issue by kzc** [fabiosantoscode/uglify-es#6]
Original issue: https://github.com/mishoo/UglifyJS2/issues/3010

The fix requires to cherry pick this commit from `uglify-js` master:

https://github.com/mishoo/UglifyJS2/commit/0c4f315c026e6

as noted here:

https://github.com/mishoo/UglifyJS2/issues/3010#issuecomment-373957512

**Comment by fabiosantoscode** [comment]
Cherry-picked in :)
