### ISSUE TITLE
arrow method with single arg named async breaks parsing

### ISSUE THREAD

**Issue by kzc** [fabiosantoscode/uglify-es#7]
Original issue: https://github.com/mishoo/UglifyJS2/issues/3079

Patch hasn't been applied to this repo: 

https://github.com/mishoo/UglifyJS2/issues/3079#issuecomment-380697571

**Comment by kzc** [comment]
Thanks @fabiosantoscode 

Since the commit log serves as the only project change log, would you consider making future commit messages describe the issues being fixed?

**Comment by fabiosantoscode** [comment]
Sure @kzc
